Blog/urls.py
from django.urls import path
from . import views

app_name = 'Blog'

urlpatterns = [
    path('pages/<int:page_id>/', views.page_detail, name='page_detail'),
    path('', views.blog_list, name='blog_list'),
    path('Blog/create/', views.blog_create, name='blog_create'),
    path('create/', views.blog_create, name='blog_create'),
    path('pages/create/', views.page_create, name='page_create'),
    path('blog_edit/<int:blog_id>/', views.blog_edit, name='blog_edit'),
    path('blog_delete/<int:blog_id>/', views.blog_delete, name='blog_delete'),

]

Melfa/urls.py
from django.urls import path
from .views import (pagina_menu_view, ClienteList, ClienteCreate,
    ClienteEditView, ClienteDeleteView, ProveedorList, ProveedorCreate,
    ProveedorEditView, ProveedorDeleteView, PaginaOrdenesCompraView,
    PaginaOrdenesCompraListView, SubirOrdenCompraExitosa, subir_orden_compra,BorrarOrdenCompraView)
from . import views

app_name = 'Melfa' 

urlpatterns = [
    path('menu/', pagina_menu_view, name='menu'),
    path('clientes_list/', ClienteList.as_view(), name='cliente_list'),
    path('cliente_create/', ClienteCreate.as_view(), name='cliente_create'),
    path('editar_cliente/<pk>/', ClienteEditView.as_view(), name='editar_cliente'),
    path('borrar_cliente/<pk>/', ClienteDeleteView.as_view(), name='borrar_cliente'),
    path('proveedores_list/', ProveedorList.as_view(), name='proveedor_list'),
    path('proveedor_create/', ProveedorCreate.as_view(), name='proveedor_create'),
    path('editar_proveedor/<pk>/', ProveedorEditView.as_view(), name='editar_proveedor'),
    path('borrar_proveedor/<pk>/', ProveedorDeleteView.as_view(), name='borrar_proveedor'),
    path('ordenes_compra/', PaginaOrdenesCompraView.as_view(), name='ordenes_compra'),
    path('ordenes_compra_list/', PaginaOrdenesCompraListView.as_view(), name='ordenes_compra_list'),
    path('subir_orden_compra_exitosa/', SubirOrdenCompraExitosa.as_view(), name='subir_orden_compra_exitosa'),
    path('subir_orden_compra/', subir_orden_compra, name='subir_orden_compra'),
    path('acerca_de_mi/', views.about_me_view, name='acerca_de_mi'),
    path('buscar_orden_compra/', views.BuscarOrdenCompraView.as_view(), name='buscar_orden_compra'),
    path('borrar_orden_compra/<int:pk>/', BorrarOrdenCompraView.as_view(), name='borrar_orden_compra'),

]

ProytectoFinal/urls.py
from django.contrib import admin
from django.urls import include, path
from cuentas.views import PaginaInicioView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cuentas/', include('cuentas.urls')),
    path('', PaginaInicioView.as_view(), name='inicio'),
    path('Melfa/', include('Melfa.urls')), # Corregido aquí
    path('Blog/', include('Blog.urls', namespace='Blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Blog/models.py
# Importamos el módulo "models" de Django, que nos permite trabajar con modelos en la base de datos.
from django.db import models

# Creamos una clase "Blog" que hereda de "models.Model". Esto define una tabla "Blog" en la base de datos.
class Blog(models.Model):
    # Definimos los campos de la tabla, especificando su tipo y restricciones.
    title = models.CharField(max_length=200)        # Campo para el título, con una longitud máxima de 200 caracteres.
    subtitle = models.CharField(max_length=200)     # Campo para el subtítulo, con una longitud máxima de 200 caracteres.
    body = models.TextField()                       # Campo para el cuerpo del blog, que puede contener mucho texto.
    author = models.CharField(max_length=100)       # Campo para el autor, con una longitud máxima de 100 caracteres.
    date = models.DateField(auto_now_add=True)      # Campo para la fecha, se configura automáticamente cuando se crea el objeto.
    image = models.ImageField(upload_to='blog_images/') # Campo para la imagen, las imágenes se guardarán en el directorio 'blog_images/'.

    # Definimos una función especial llamada "__str__" que retorna una representación en cadena del objeto.
    # En este caso, la representación será el título del blog.
    def __str__(self):
        return self.title

# Creamos una clase similar para una tabla "Page" en la base de datos.
class Page(models.Model):
    title = models.CharField(max_length=200)        # Campo para el título, con una longitud máxima de 200 caracteres.
    content = models.TextField()                   # Campo para el contenido de la página, que puede contener mucho texto.

    # Nuevamente, definimos una función "__str__" para retornar una representación en cadena del objeto.
    # Aquí, la representación será el título de la página.
    def __str__(self):
        return self.title

Blog/forms.py
# Primero, importamos la biblioteca "forms" de Django para trabajar con formularios.
# También importamos los modelos "Blog" y "Page" desde el archivo actual del directorio (indicado con el punto).
from django import forms
from .models import Blog, Page

# Creamos una clase llamada "BlogForm" que hereda de "forms.ModelForm".
# Esta clase se utilizará para crear un formulario basado en el modelo "Blog".
class BlogForm(forms.ModelForm):
    # Dentro de la clase, definimos una subclase "Meta" que contiene información adicional sobre el formulario.
    class Meta:
        # Indicamos que el modelo en el que se basa el formulario es "Blog".
        model = Blog
        # Especificamos los campos del modelo que queremos incluir en el formulario.
        fields = ['title', 'subtitle', 'body', 'author', 'image'] 
        # Definimos las etiquetas que se mostrarán junto a cada campo en el formulario.
        labels = {
            'title': 'Título',
            'subtitle': 'Subtítulo',
            'body': 'Cuerpo',
            'author': 'Autor',
            'image': 'Imagen',
        }

# De manera similar, creamos una clase "PageForm" que se basa en el modelo "Page".
# Esta clase define un formulario para crear o editar páginas.
class PageForm(forms.ModelForm):
    # Nuevamente, usamos una subclase "Meta" para contener la información adicional del formulario.
    class Meta:
        # Indicamos que el modelo en el que se basa el formulario es "Page".
        model = Page
        # Especificamos los campos del modelo que queremos incluir en el formulario.
        fields = ['title', 'content']

Blog/views.py
# Importaciones necesarias para manejar las vistas, modelos y formularios.
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseForbidden
from django.contrib.auth.decorators import login_required
from .models import Blog, Page
from .forms import BlogForm, PageForm

def blog_list(request):
    blogs = Blog.objects.all()  # Obtiene todos los blogs.
    return render(request, 'blog_list.html', {'blogs': blogs})

def page_detail(request, page_id):
    page = get_object_or_404(Page, pk=page_id)
    return render(request, 'pagina_detalle.html', {'page': page})

@login_required
def blog_create(request):
    if not request.user.is_superuser:
        return HttpResponseForbidden()
    if request.method == 'POST':
        form = BlogForm(request.POST, request.FILES)
        if form.is_valid():
            new_blog = form.save(commit=False)
            new_blog.author = request.user
            new_blog.save()
            new_page = Page(title=new_blog.title, content=new_blog.body)
            new_page.save()
            return redirect('Blog:blog_list')
    else:
        form = BlogForm()
    return render(request, 'blog_crear.html', {'form': form})

@login_required
def page_create(request):
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            new_page = form.save()
            return redirect('Blog:pagina_detalle', new_page.id)
    else:
        form = PageForm()
    return render(request, 'page_crear.html', {'form': form})

@login_required
def blog_edit(request, blog_id):
    if not request.user.is_superuser:  # Comprueba si el usuario es un superusuario.
        return HttpResponseForbidden()
    blog = get_object_or_404(Blog, pk=blog_id)
    if request.method == "POST":
        form = BlogForm(request.POST, instance=blog)
        if form.is_valid():
            form.save()
            return redirect('Blog:blog_list')
    else:
        form = BlogForm(instance=blog)
    return render(request, 'blog_editar.html', {'form': form})

@login_required
def blog_delete(request, blog_id):
    if not request.user.is_superuser:  # Comprueba si el usuario es un superusuario.
        return HttpResponseForbidden()
    blog = get_object_or_404(Blog, pk=blog_id)
    if request.method == "POST":
        blog.delete()  # Borra el blog.
        return redirect('Blog:blog_list')
    return render(request, 'blog_borrar.html', {'blog': blog})

Blog/templates/blog_borrar.html
{% load static %} <!-- Carga la etiqueta estática de Django para acceder a archivos estáticos, como imágenes -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> <!-- Ajusta la página para dispositivos móviles -->
    <title>Eliminar Blog</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.9.3/css/bulma.min.css"> <!-- Utiliza Bulma CSS para estilización -->
    <style>
        /* Definición de estilos básicos */
        body {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }

        h1 {
            font-size: 2rem;
            margin-bottom: 1rem;
        }

        p {
            font-size: 1.2rem;
            margin-bottom: 1.5rem;
        }

        form {
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        button, a {
            margin-top: 1rem;
        }

        .peligro {
            width: 100px; /* Ajusta el tamaño del logo según tus necesidades */
            margin-bottom: 1rem;
        }
    </style>
</head>
<body>
    <div class="logo">
        <img src="{% static 'images/peligro.png' %}" alt="Logo de Mi Empresa"> <!-- Imagen estática de la carpeta 'images' -->
    </div>
    <h1>Eliminar Publicacion</h1>
    <p>¿Estás seguro de que quieres eliminar la publicación"{{ blog.title }}"?</p> <!-- Interpolación del título del blog -->
    <form method="post"> <!-- Formulario POST para eliminar el blog -->
        {% csrf_token %} <!-- Token de seguridad requerido en formularios POST en Django -->
        <button class="button is-danger" type="submit">Sí, eliminar</button> <!-- Botón para confirmar la eliminación -->
        <a class="button is-warning" href="{% url 'Blog:blog_list' %}">Cancelar</a> <!-- Enlace para cancelar la acción -->
    </form>
</body>
</html>

Blog/templates/blog_crear.html
{% load static %} <!-- Carga la etiqueta estática de Django para acceder a archivos estáticos -->

<!DOCTYPE html>
<html>
<head>
    <!-- Enlace al archivo Bulma CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.9.3/css/bulma.min.css">
    <style>
        html, body {
            height: 100%;
            margin: 0;
        }
        .main-container {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            height: 100%;
        }
    </style>
</head>
<body>
    <div class="main-container">
        <header class="header">
            <div class="logo-container has-text-centered">
                <img src="{% static 'images/logo.png' %}" alt="Logo de Mi Empresa" class="mt-3">
            </div>
        </header>
        <div class="section">
            <div class="container">
                <h2 class="title">Nuevo Papel</h2>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="field">
                            <label class="label">{{ field.label_tag }}</label>
                            <div class="control">
                                {{ field }}
                            </div>
                        </div>
                    {% endfor %}
                    <div class="field">
                        <div class="control">
                            <button type="submit" class="button is-warning">
                                <i class="fas fa-save"></i> Crear
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>
</html>

Blog/templates/blog_editar.html
{% load static %} <!-- Carga las etiquetas para usar archivos estáticos en Django -->

<!DOCTYPE html>
<html>
<head>
    <title>Editar Publicacion</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.9.3/css/bulma.min.css"> <!-- Enlaza con Bulma CSS para estilizar la página -->
</head>
<body>
    <section class="section"> <!-- Sección principal de la página -->
        <div class="container"> <!-- Contenedor central para alinear y centrar contenido -->
            <div class="columns is-centered"> <!-- Crea una estructura de columnas, y centra el contenido -->
                <div class="column is-half"> <!-- Define la columna a la mitad de ancho del contenedor -->
                    <div style="text-align: center;"> <!-- Centra el contenido dentro del div -->
                        <img src="{% static 'images/logo.png' %}" alt="Logo de Mi Empresa"> <!-- Muestra el logo estático de la carpeta 'images' -->
                    </div>
                    <h1 class="title has-text-centered">Editar Publicacion</h1> <!-- Título de la sección, centrado -->

                    <form method="POST"> <!-- Formulario para enviar datos de la edición, usando método POST -->
                        {% csrf_token %} <!-- Token de seguridad requerido para formularios POST en Django -->

                        {% for field in form %} <!-- Bucle que recorre todos los campos del formulario -->
                        <div class="field"> <!-- Cada campo del formulario se encapsula en un div 'field' de Bulma -->
                            <label class="label">{{ field.label }}</label> <!-- Etiqueta para el campo del formulario -->

                            <div class="control"> <!-- Contenedor para elementos de control, como entradas de texto o áreas de texto -->
                                {% if field.name == "body" %} <!-- Si el nombre del campo es 'body', use un área de texto -->
                                <textarea class="textarea" name="{{ field.name }}" minlength="2000" required>{{ field.value|default_if_none:"" }}</textarea>
                                {% else %} <!-- Para otros campos, use un input de texto -->
                                <input class="input" type="text" name="{{ field.name }}" value="{{ field.value|default_if_none:"" }}" required>
                                {% endif %}
                            </div>
                        </div>
                        {% endfor %}

                        <div class="has-text-centered"> <!-- Centra el contenido dentro del div -->
                            <button class="button is-warning" type="submit">Guardar Cambios</button> <!-- Botón para enviar el formulario -->
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
</body>
</html>

Blog/templates/blog_list.html
{% load static %} <!-- Carga las etiquetas para usar archivos estáticos en Django -->

<!DOCTYPE html>
<html>
<head>
    <title>Papeles</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.9.3/css/bulma.min.css"> <!-- Enlaza con Bulma CSS para estilizar la página -->
    <style>
        .header { /* Estilo para el encabezado */
            text-align: center; /* Centra el texto en el encabezado */
            padding: 20px; /* Agrega un relleno al encabezado */
        }
    </style>
</head>
<body>
    <div class="header has-text-centered"> <!-- Encabezado, centrado horizontalmente -->
        <img src="{% static 'images/logo.png' %}" alt="Logo de Mi Empresa"> <!-- Logo de la empresa -->
    </div>

    <nav class="navbar is-warning is-centered" role="navigation" aria-label="main navigation"> <!-- Navegación en el sitio con estilo Bulma -->
        <div class="navbar-menu">
            <div class="navbar-start">
                <a class="navbar-item" href="{% url 'Melfa:menu' %}">Volver al Menú Principal</a> <!-- Enlace para regresar al menú principal -->
            </div>
            <div class="navbar-end">
                <a class="navbar-item" href="{% url 'Blog:blog_create' %}">Crear nuevo blog</a> <!-- Enlace para crear un nuevo blog -->
            </div>
        </div>
    </nav>

    <section class="section"> <!-- Sección principal -->
        <div class="container">
            <div class="columns is-multiline is-centered"> <!-- Columnas, permitiendo múltiples líneas y centradas -->
                {% for blog in blogs %} <!-- Bucle para iterar sobre cada blog en la lista de blogs -->
                <div class="column is-one-third"> <!-- Columna individual para cada blog -->
                    <div class="card"> <!-- Tarjeta para presentar el blog -->
                        <div class="card-image">
                            <figure class="image is-140x140"> <!-- Imagen del blog con dimensiones específicas -->
                                <img src="{{ blog.image.url }}" alt="{{ blog.title }}">
                            </figure>
                        </div>
                        <div class="card-content"> <!-- Contenido de la tarjeta -->
                            <h2 class="title">{{ blog.title }}</h2> <!-- Título del blog -->
                            <p class="subtitle">{{ blog.subtitle }}</p> <!-- Subtítulo del blog -->
                            <p>{{ blog.author }}</p> <!-- Autor del blog -->
                            <a class="button is-primary" href="{% url 'Blog:page_detail' blog.id %}">Leer más</a> <!-- Botón para leer más -->
                            <a class="button is-warning" href="{% url 'Blog:blog_edit' blog.id %}">Edit</a> <!-- Botón para editar -->
                            <a class="button is-danger" href="{% url 'Blog:blog_delete' blog.id %}">Delete</a> <!-- Botón para eliminar -->
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
</body>
</html>

Blog/templates/pagina_detalle.html
{% load static %} <!-- Carga las etiquetas para usar archivos estáticos en Django -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Page Detail</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css"> <!-- Enlace a la hoja de estilo de Bootstrap -->
    <style>
        body {
            padding-top: 2rem; /* Agrega relleno en la parte superior del cuerpo */
        }
    </style>
</head>
<body>
    <div class="container"> <!-- Contenedor principal -->
        <div class="row justify-content-center"> <!-- Fila, centrada horizontalmente -->
            <div class="col-md-8"> <!-- Columna con ancho definido -->
                <div class="card"> <!-- Tarjeta para presentar la página de blog -->
                    <div class="card-body"> <!-- Cuerpo de la tarjeta -->
                        <div class="text-center mb-3"> <!-- Logotipo de la empresa, centrado -->
                            <img src="{% static 'images/logo.png' %}" alt="Logo de Mi Empresa" class="img-fluid" style="max-width: 200px;">
                        </div>
                        <h1 class="card-title text-center mb-4">{{ page.title }}</h1> <!-- Título de la página, centrado -->
                        <p class="card-text">{{ page.content }}</p> <!-- Contenido de la página -->
                        <a href="{% url 'Blog:blog_list' %}" class="btn btn-primary">Volver a la lista de blogs</a> <!-- Enlace para volver a la lista de blogs -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>