Blog/urls.py
from django.urls import path
from . import views

app_name = 'Blog'

urlpatterns = [
    path('pages/<int:page_id>/', views.page_detail, name='page_detail'),
    path('', views.blog_list, name='blog_list'),
    path('Blog/create/', views.blog_create, name='blog_create'),
    path('create/', views.blog_create, name='blog_create'),
    path('pages/create/', views.page_create, name='page_create'),
    path('blog_edit/<int:blog_id>/', views.blog_edit, name='blog_edit'),
    path('blog_delete/<int:blog_id>/', views.blog_delete, name='blog_delete'),

]

Melfa/urls.py
from django.urls import path
from .views import (pagina_menu_view, ClienteList, ClienteCreate,
    ClienteEditView, ClienteDeleteView, ProveedorList, ProveedorCreate,
    ProveedorEditView, ProveedorDeleteView, PaginaOrdenesCompraView,
    PaginaOrdenesCompraListView, SubirOrdenCompraExitosa, subir_orden_compra,BorrarOrdenCompraView)
from . import views

app_name = 'Melfa' 

urlpatterns = [
    path('menu/', pagina_menu_view, name='menu'),
    path('clientes_list/', ClienteList.as_view(), name='cliente_list'),
    path('cliente_create/', ClienteCreate.as_view(), name='cliente_create'),
    path('editar_cliente/<pk>/', ClienteEditView.as_view(), name='editar_cliente'),
    path('borrar_cliente/<pk>/', ClienteDeleteView.as_view(), name='borrar_cliente'),
    path('proveedores_list/', ProveedorList.as_view(), name='proveedor_list'),
    path('proveedor_create/', ProveedorCreate.as_view(), name='proveedor_create'),
    path('editar_proveedor/<pk>/', ProveedorEditView.as_view(), name='editar_proveedor'),
    path('borrar_proveedor/<pk>/', ProveedorDeleteView.as_view(), name='borrar_proveedor'),
    path('ordenes_compra/', PaginaOrdenesCompraView.as_view(), name='ordenes_compra'),
    path('ordenes_compra_list/', PaginaOrdenesCompraListView.as_view(), name='ordenes_compra_list'),
    path('subir_orden_compra_exitosa/', SubirOrdenCompraExitosa.as_view(), name='subir_orden_compra_exitosa'),
    path('subir_orden_compra/', subir_orden_compra, name='subir_orden_compra'),
    path('acerca_de_mi/', views.about_me_view, name='acerca_de_mi'),
    path('buscar_orden_compra/', views.BuscarOrdenCompraView.as_view(), name='buscar_orden_compra'),
    path('borrar_orden_compra/<int:pk>/', BorrarOrdenCompraView.as_view(), name='borrar_orden_compra'),

]

ProytectoFinal/urls.py
from django.contrib import admin
from django.urls import include, path
from cuentas.views import PaginaInicioView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cuentas/', include('cuentas.urls')),
    path('', PaginaInicioView.as_view(), name='inicio'),
    path('Melfa/', include('Melfa.urls')), # Corregido aquí
    path('Blog/', include('Blog.urls', namespace='Blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cuentas/urls.py
from django.urls import path
from . import views
from .views import user_profile, PaginaInicioView

app_name = 'cuentas'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('registro/', views.user_register, name='registro'),
    path('editar/', views.user_edit, name='editar'),
    path('perfil/', user_profile, name='perfil'),
    path('inicio/', PaginaInicioView.as_view(), name='inicio'),
]

Melfa/models.py
# models.py

from django.db import models
from django.conf import settings


class Cliente(models.Model):
    nombre = models.CharField(max_length=100)
    numero_cliente = models.IntegerField()
    email = models.EmailField()
    direccion = models.CharField(max_length=200)
    telefono = models.CharField(max_length=20)

    def __str__(self):
        return self.nombre

class Proveedor(models.Model):
    nombre = models.CharField(max_length=100)
    insumo = models.CharField(max_length=100)
    email = models.EmailField()
    direccion = models.CharField(max_length=200)
    telefono = models.CharField(max_length=20)

    def __str__(self):
        return self.nombre


class OrdenDeCompra(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    numero_orden = models.CharField(max_length=50)
    archivo = models.FileField(upload_to='ordenes_compra/')
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.cliente} - {self.numero_orden}'
    

Melfa/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required


class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['nombre', 'numero_cliente', 'email', 'direccion', 'telefono']

class ProveedorForm(forms.ModelForm):
    class Meta:
        model = Proveedor
        fields = ['nombre', 'insumo', 'email', 'direccion', 'telefono']

class RegistroForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('Este nombre de usuario ya está en uso.')
        return username

class OrdenDeCompraForm(forms.ModelForm):
    cliente = forms.ModelChoiceField(
        queryset=Cliente.objects.all(),
        widget=forms.Select(attrs={'class': 'input', 'required': True})
    )
    
    class Meta:
        model = OrdenDeCompra
        fields = ['cliente', 'numero_orden', 'archivo']
        widgets = {
            'numero_orden': forms.TextInput(attrs={'class': 'input', 'required': True}),
        }

Melfa/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib import messages
from .models import Cliente, Proveedor, OrdenDeCompra
from .forms import ClienteForm, ProveedorForm, OrdenDeCompraForm
from django.views import View
from django.shortcuts import get_object_or_404

# Vista para el menú principal - requiere que el usuario esté autenticado
@login_required
def pagina_menu_view(request):
    return render(request, 'menu.html')


# Vista de la lista de clientes
class ClienteList(ListView):
    model = Cliente
    template_name = "clientes_list.html"
    context_object_name = "clientes"

    def get_queryset(self):
        queryset = super().get_queryset()
        messages.info(self.request, f"Se encontraron {queryset.count()} clientes.")
        return queryset


# Vista para crear un nuevo cliente
class ClienteCreate(CreateView):
    model = Cliente
    form_class = ClienteForm
    template_name = "cliente_form.html"
    success_url = reverse_lazy('Melfa:cliente_list')


# Vista para editar un cliente
class ClienteEditView(UpdateView):
    model = Cliente
    template_name = 'editar_cliente.html'
    form_class = ClienteForm
    success_url = reverse_lazy('Melfa:cliente_list')


# Vista para eliminar un cliente
class ClienteDeleteView(DeleteView):
    model = Cliente
    template_name = 'cliente_confirma_borrado.html'
    success_url = reverse_lazy('Melfa:cliente_list')


# Vista de la lista de proveedores
class ProveedorList(ListView):
    model = Proveedor
    template_name = "proveedor_list.html"
    context_object_name = "proveedores"

    def get_queryset(self):
        queryset = super().get_queryset()
        messages.info(self.request, f"Se encontraron {queryset.count()} proveedores.")
        return queryset

# Vista para crear un nuevo proveedor
class ProveedorCreate(CreateView):
    model = Proveedor
    form_class = ProveedorForm
    template_name = "proveedor_form.html"
    success_url = reverse_lazy('Melfa:proveedor_list')


# Vista para editar un proveedor
class ProveedorEditView(UpdateView):
    model = Proveedor
    template_name = 'editar_proveedor.html'
    form_class = ProveedorForm
    success_url = reverse_lazy('Melfa:proveedor_list')


# Vista para eliminar un proveedor
class ProveedorDeleteView(DeleteView):
    model = Proveedor
    template_name = 'proveedor_confirmar_borrado.html'
    success_url = reverse_lazy('Melfa:proveedor_list')

# Vista para la página de órdenes de compra
class PaginaOrdenesCompraView(View):
    # Método GET para mostrar la página
    def get(self, request):
        form = OrdenDeCompraForm()
        ordenes = OrdenDeCompra.objects.all()
        return render(request, 'ordenes_compra.html', {'form': form, 'ordenes': ordenes})
    # Método POST para recibir los datos del formulario
    def post(self, request):
        form = OrdenDeCompraForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Orden de compra subida correctamente.')
            return redirect('Melfa:subir_orden_compra_exitosa')
        ordenes = OrdenDeCompra.objects.all()
        return render(request, 'ordenes_compra.html', {'form': form, 'ordenes': ordenes})

# Vista para mostrar una lista de órdenes de compra
class PaginaOrdenesCompraListView(View):
    def get(self, request):
        ordenes = OrdenDeCompra.objects.all()
        return render(request, 'ordenes_compra_list.html', {'ordenes': ordenes})


# Vista para la página de subida exitosa de la orden de compra
class SubirOrdenCompraExitosa(View):
    def get(self, request):
        return render(request, 'subir_orden_compra_exitosa.html')


# Vista para subir una orden de compra
def subir_orden_compra(request):
    if request.method == 'POST':
        form = OrdenDeCompraForm(request.POST, request.FILES)
        if form.is_valid():
            orden_de_compra = form.save(commit=False)
            orden_de_compra.usuario = request.user  # Asigna el usuario actual
            orden_de_compra.save()
            messages.success(request, 'Orden de compra subida correctamente.')
            return redirect('Melfa:subir_orden_compra_exitosa')
    else:
        form = OrdenDeCompraForm()
    return render(request, 'subir_orden_compra.html', {'form': form})


# Vista para la página "Acerca de mí"
def about_me_view(request):
    return render(request, 'acerca_de_mi.html')


# Vista para borrar una orden de compra
class BorrarOrdenCompraView(View):
    def get(self, request, pk):
        orden = get_object_or_404(OrdenDeCompra, pk=pk)
        return render(request, 'borrar_orden_compra.html', {'orden': orden})

    def post(self, request, pk):
        orden = get_object_or_404(OrdenDeCompra, pk=pk)
        orden.delete()
        return redirect('Melfa:ordenes_compra_list')

# Vista para buscar una orden de compra
class BuscarOrdenCompraView(View):
    def get(self, request):
        return render(request, 'buscar_orden_compra.html')

    def post(self, request):
        numero_orden = request.POST.get('numero_orden')
        ordenes = OrdenDeCompra.objects.filter(numero_orden__icontains=numero_orden)
        return render(request, 'buscar_orden_compra.html', {'ordenes': ordenes})

Melfa/templates/clientes_list.html
{% load static %} <!-- Carga los archivos estáticos, como imágenes y CSS -->

<!DOCTYPE html>
<html>
<head>
    <title>Lista de clientes</title>
    <!-- Estilos CSS, incluyendo Bulma y Font Awesome -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bulma.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
</head>
<body>
    
    <!-- Encabezado con el logo -->
    <header class="hero is-white is-bold is-small">
        <div class="hero-body">
            <div class="container has-text-centered">
                <img src="{% static 'images/logo.png' %}" alt="Logo de Mi Empresa" class="logo-image" style="filter: brightness(85%);">
            </div>
        </div>
    </header>

    <!-- Título de la página -->
    <section class="section">
        <div class="container">
            <h1 class="title is-1 has-text-centered">Lista de Clientes</h1>
        </div>
    </section>

    <!-- Contenedor de la tabla -->
    <div class="table-container">
        {% if clientes %} <!-- Si hay clientes disponibles -->
            <table class="table is-fullwidth">
                <thead>
                    <!-- Encabezados de las columnas -->
                    <tr>
                        <th>Nombre</th>
                        <th>Número de cliente</th>
                        <th>Email</th>
                        <th>Dirección</th>
                        <th>Teléfono</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    <!-- Itera sobre cada cliente y muestra sus detalles en una fila -->
                    {% for cliente in clientes %}
                    <tr>
                        <td>{{ cliente.nombre }}</td>
                        <td>{{ cliente.numero_cliente }}</td>
                        <td>{{ cliente.email }}</td>
                        <td>{{ cliente.direccion }}</td>
                        <td>{{ cliente.telefono }}</td>
                        <td>
                            <!-- Enlaces para editar y borrar el cliente -->
                            <a href="{% url 'Melfa:editar_cliente' cliente.pk %}" class="button is-warning"><i class="fas fa-pencil-alt"></i> Editar</a>
                            <a href="{% url 'Melfa:borrar_cliente' cliente.pk %}" class="button is-danger"><i class="fas fa-trash"></i> Borrar</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>No hay clientes cargados.</p> <!-- Si no hay clientes disponibles -->
        {% endif %}
    </div>

    <!-- Enlaces para añadir un nuevo cliente y volver al menú principal -->
    <a href="{% url 'Melfa:cliente_create' %}" class="button is-warning"><i class="fas fa-plus"></i> Añadir cliente</a>
    <a href="{% url 'Melfa:menu' %}" class="button is-primary">
        <i class="fas fa-arrow-left"></i> Volver al Menú Principal
    </a>
    
    <!-- Enlace al archivo Bulma JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.9.3/js/bulma.min.js"></script>
</body>
</html>

Melfa/templates/edit_user_profile.html
{% block content %} <!-- Inicio del bloque de contenido, para ser insertado en una plantilla base -->

  <h1>Edit User Profile</h1> <!-- Título de la página -->

  <!-- Inicio del formulario para editar el perfil del usuario -->
  <form method="post" enctype="multipart/form-data"> <!-- El atributo 'enctype' permite el envío de archivos en el formulario -->

    {% csrf_token %} <!-- Token CSRF para proteger el formulario contra ataques maliciosos -->

    {{ user_form.as_p }} <!-- Renderizar el formulario del usuario como una serie de párrafos. 'user_form' debe ser pasado al contexto de la plantilla en la vista -->

    {{ profile_form.as_p }} <!-- Renderizar el formulario del perfil como una serie de párrafos. 'profile_form' debe ser pasado al contexto de la plantilla en la vista -->

    <button type="submit" class="btn btn-primary">Save Changes</button> <!-- Botón para enviar el formulario -->

  </form> <!-- Fin del formulario -->

{% endblock %} <!-- Fin del bloque de contenido -->

Melfa/templates/menu.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Bienvenidos a Artes Graficas Melfa S.A</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Simple line icons-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.5.5/css/simple-line-icons.min.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="/static/css/styles.css" rel="stylesheet" />
    </head>
    <style>
        .bg-black {
            background-color: black;
        }
    
        .bg-black h3,
        .bg-black h2,
            .bg-black .text-white {
            color: orange;
        }

        .text-orange {
            color: orange;
        }
    </style>
    <body id="page-top">
        <!-- Navegación-->
        <a class="menu-toggle rounded" href="#"><i class="fas fa-bars"></i></a>
        <nav id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand"><a href="#page-top">Artes Graficas Melfa</a></li>
                <li class="sidebar-nav-item"><a href="{% url 'Blog:blog_list' %}">Papeles</a></li>
                <li class="sidebar-nav-item"><a href="{% url 'Melfa:cliente_list' %}">Clientes</a></li>
                <li class="sidebar-nav-item"><a href="{% url 'Melfa:proveedor_list' %}">Proveedores</a></li>
                <li class="sidebar-nav-item"><a href="{% url 'Melfa:ordenes_compra_list' %}">Órdenes de Compra</a></li>
                <li class="sidebar-nav-item"><a href="{% url 'Melfa:acerca_de_mi' %}">Acerca de Mí</a></li>
                <li class="sidebar-nav-item"><a href="{% url 'cuentas:perfil' %}">Perfil</a></li>
                <li class="sidebar-nav-item"><a href="{% url 'admin:index' %}">Admin</a></li>
                <li class="sidebar-nav-item"><a href="{% url 'cuentas:inicio' %}">logout</a></li>
                
            </ul>
        </nav>
        <!-- Encabezado-->
        <header class="masthead d-flex align-items-center">
            <div class="container px-4 px-lg-5 text-center">
                
                <a class="btn btn-primary btn-orange" href="#about">Descubre Más</a>
            </div>
        </header>
        
        <!-- Acerca de-->
        <section class="content-section bg-light" id="about">
            <div class="container px-4 px-lg-5 text-center">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-lg-10">
                        <h1 class="mb-1" style="color: #FFA500;">Artes Graficas Melfa S.A</h1>
                        <h3 class="mb-5" style="color: #FFA500;"><em>Su etiqueta es nuestro desafío</em></h3>

                        <h2>    Artes Gráficas Melfa S.A. es una empresa dedicada a lograr la excelencia en la producción de etiquetas autoadhesivas. Nuestro objetivo es brindarle la mejor y más ágil atención y un producto de gran calidad. Para ello, incorporamos nueva tecnología de forma constante, para estar al día con los últimos procesos que permiten una variedad de posibilidades.</h2>
                        
                        <a class="btn btn-dark btn-xl" href="#services">Lo que Ofrecemos</a>
                    </div>
                </div>
            </div>
        </section>
        <!-- Servicios-->
        <section class="content-section bg-black text-white text-center" id="services">
            <div class="container px-4 px-lg-5">
                <div class="content-section-heading">
                    <h3 class="text-primary mb-0">Servicios</h3>
                    <h2 class="mb-5">Lo que Ofrecemos</h2>
                </div>
                <div class="row gx-4 gx-lg-5">
                    <div class="col-lg-3 col-md-6 mb-5 mb-lg-0">
                        <span class="service-icon rounded-circle mx-auto mb-3"><i class="icon-printer"></i></span>
                        <h3 class="text-orange">Impresion Flexo</h3>
                        <p class="text-faded mb-0">¡La mejor tecnologia en impresion, aplicada a tu etiqueta!</p>
                    </div>
                    <div class="col-lg-3 col-md-6 mb-5 mb-lg-0">
                        <span class="service-icon rounded-circle mx-auto mb-3"><i class="icon-pencil"></i></span>
                        <h3 class="text-orange">Diseño</h3>
                        <p class="text-faded mb-0">Nuetros diseñadores adaptan tu idea y la hacen realidad</p>
                    </div>
                    <div class="col-lg-3 col-md-6 mb-5 mb-md-0">
                        <span class="service-icon rounded-circle mx-auto mb-3"><i class="icon-calendar"></i></span>
                        <h3 class="text-orange">Entrega Rapida</h3>
                        <p class="text-faded mb-0">
                            COntamos con tecnologia que nos permite responder rapidamente a los pedidos de nuestros clientes.
                            <i class="fas fa-heart"></i>
                            Start Bootstrap!
                        </p>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <span class="service-icon rounded-circle mx-auto mb-3"><i class="icon-eye"></i></span>
                        <h3 class="text-orange">Calidad</h3>
                        <p class="text-faded mb-0">Contamos con el mejor control de Calidad, ya que contamos con certificacion BRCGS - Norma mundial de seguridad alimentaria </p>
                    </div>
                </div>
            </div>
        </section>
        <!-- Anuncio-->
        <section class="callout">
            <div class="container px-4 px-lg-5 text-center">
                <h2 class="mx-auto mb-5">
                 Nuestra Tecnologia
                </h2>
                <a class="btn btn-primary btn-xl" href="https://www.nilpeter.com/Products/Presses/Flexo/FA-Line">Conoce Mas</a>
            </div>
        </section>
        <!-- Portfolio-->
        <section class="content-section" id="portfolio">
            <div class="container px-4 px-lg-5">
                <div class="content-section-heading text-center">
                    <h3 class="text-secondary mb-0">Portafolio</h3>
                    <h2 class="mb-5">Proyectos Recientes</h2>
                </div>
                <div class="row gx-4 gx-lg-5 no-gutters mb-4 mb-lg-5">
                    <div class="col-lg-6"><img class="img-fluid" src="/static/assets/img/1.jpg" alt="..." /></div>
                    <div class="col-lg-6 order-lg-first">
                        <div class="bg-black text-center h-100 project">
                            <div class="d-flex h-100">
                                <div class="project-text w-100 my-auto text-center text-lg-left">
                                    <h4 class="text-white">Diseño de la imagen del vino del prestigioso director técnico Marcelo Gallardo</h4>
                                    <p class="mb-0 text-white-50">– BY BODEGA NORTON –</p>
                                    <hr class="d-none d-lg-block mb-0 ms-0" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row gx-4 gx-lg-5 no-gutters">
                    <div class="col-lg-6"><img class="img-fluid" src="/static/assets/img/2.jpg" alt="..." /></div>
                    <div class="col-lg-6">
                        <div class="bg-black text-center h-100 project">
                            <div class="d-flex h-100">
                                <div class="project-text w-100 my-auto text-center text-lg-right">
                                    <h4 class="text-white">Rediseño de los varietales, actualizando su identidad de marca y sus códigos visuales ganando destaque y diferenciación entre sus varietales.</h4>
                                    <p class="mb-0 text-white-50">– BY PASCUAL TOSO –</p>
                                    <hr class="d-none d-lg-block mb-0 me-0" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
              
                <div class="row gx-4 gx-lg-5 no-gutters">
                    <div class="col-lg-6"><img class="img-fluid" src="/static/assets/img/4.jpg" alt="..." /></div>
                    <div class="col-lg-6 order-lg-first">
                        <div class="bg-black text-center h-100 project">
                            <div class="d-flex h-100">
                                <div class="project-text w-100 my-auto text-center text-lg-right">
                                    <h4 class="text-white">Un espumante para celebrar momentos únicos. Edición Especial de este clásico espumante para esos momentos de unión, celebración y disfrute.</h4>
                                    <p class="mb-0 text-white-50">– BY FEDERICO DE ALVEAR –</p>
                                    <hr class="d-none d-lg-block mb-0 me-0" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
       
        <!-- Pie de Página-->
        <footer class="footer text-center">
            <div class="container px-4 px-lg-5">
                <ul class="list-inline mb-5">
                    <li class="list-inline-item">
                        <a class="social-link rounded-circle text-white mr-3" href="https://www.facebook.com/artesgraficasmelfa"><i class="icon-social-facebook"></i></a>
                    </li>
                    <li class="list-inline-item">
                        <a class="social-link rounded-circle text-white mr-3" href="https://www.instagram.com/artesgraficasmelfa/"><i class="icon-social-instagram"></i></a>
                    </li>
                                     
                </ul>
              
            </div>
        </footer>
        <!-- Scroll to Top Button-->
        <a class="scroll-to-top rounded" href="#page-top">
            <i class="fas fa-angle-up"></i>
        </a>
        <!-- Bootstrap core JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.bundle.min.js"></script>
        <!-- Terceros plugins (necesarios para algunos componentes)-->
        <script src="/static/js/scripts.js"></script>
    </body>
</html>

Melfa/templates/proveedor_list.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Lista de Proveedores</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bulma.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
</head>
<body>
    <!-- Encabezado con el logo -->
    <header class="hero is-white is-bold is-small">
        <div class="hero-body">
            <div class="container has-text-centered">
                <!-- Aplicamos el filtro de brillo en línea -->
                <img src="{% static 'images/logo.png' %}" alt="Logo de Mi Empresa" class="logo-image" style="filter: brightness(85%);">
            </div>
        </div>
    </header>

    <section class="section">
        <div class="container has-text-centered">
            <h1 class="title is-1">Lista de Proveedores</h1>
        </div>
    </section>

    <div class="table-container">
        {% if proveedores %}
            <table class="table is-fullwidth">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Insumo</th>
                        <th>Email</th>
                        <th>Dirección</th>
                        <th>Teléfono</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for proveedor in proveedores %}
                    <tr>
                        <td>{{ proveedor.nombre }}</td>
                        <td>{{ proveedor.insumo }}</td>
                        <td>{{ proveedor.email }}</td>
                        <td>{{ proveedor.direccion }}</td>
                        <td>{{ proveedor.telefono }}</td>
                        <td>
                            <a href="{% url 'Melfa:editar_proveedor' proveedor.pk %}" class="button is-primary"><i class="fas fa-pencil-alt"></i> Editar</a>
                            <a href="{% url 'Melfa:borrar_proveedor' proveedor.pk %}" class="button is-danger"><i class="fas fa-trash"></i> Borrar</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>No hay proveedores cargados.</p>
        {% endif %}
    </div>

    <a href="{% url 'Melfa:proveedor_create' %}" class="button is-warning"><i class="fas fa-plus"></i> Añadir Proveedor</a>
    <a href="{% url 'Melfa:menu' %}" class="button is-primary">
        <i class="fas fa-arrow-left"></i> Volver al Menú Principal
    </a>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.9.3/js/bulma.min.js"></script>
</body>
</html>